import json, os

def code_cell(source):
    return {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": source
    }

def md_cell(source):
    return {
        "cell_type": "markdown",
        "metadata": {},
        "source": source
    }

cells = []

# ── SECTION 0 header (markdown) ──────────────────────────────────────────────
cells.append(md_cell(
    "# Interpretable Deep Clustering — Paper Reconstruction\n"
    "Paper: Interpretable Deep Clustering for Tabular Data, Svirsky & Lindenbaum, ICML 2024  \n"
    "Goal: Reconstruct all 6 experiments from Section 6 using the authors' code in idc/.  \n"
    "Note: We only reconstruct IDC results. Baseline results for other methods are taken verbatim from the paper.\n\n"
    "| # | Experiment | Dataset | Paper output |\n"
    "|---|---|---|---|\n"
    "| 1 | Synthetic | Built-in generator | ACC, F1-score |\n"
    "| 2 | Interpretability quality | MNIST10K | Table 1 |\n"
    "| 3 | Real tabular data | 11 datasets | Table 2 |\n"
    "| 4 | Image domain | MNIST60K, FashionMNIST, CIFAR10 | Tables 3 & 4 |\n"
    "| 5 | Spectral bias (NUDFT) | ALLAML | Figure 4 |\n"
    "| 6 | Ablation study | MNIST60K | Table 5 |"
))

# ── CELL 1 ───────────────────────────────────────────────────────────────────
cells.append(md_cell("---\n## Section 0: Environment Setup"))

# ── CELL 2 ───────────────────────────────────────────────────────────────────
cells.append(code_cell(
    "# Uncomment to install:\n"
    "# !pip install torch pytorch-lightning==2.0.0 scikit-learn==1.1.2 scipy==1.10.0rc1 omegaconf matplotlib umap-learn torchvision munkres nfft\n"
    "\n"
    "import sys, os, warnings, zipfile\n"
    "warnings.filterwarnings('ignore')\n"
    "\n"
    "IDC_PATH = os.path.join(os.getcwd(), 'idc')\n"
    "if IDC_PATH not in sys.path:\n"
    "    sys.path.insert(0, IDC_PATH)\n"
    "\n"
    "import torch\n"
    "import numpy as np\n"
    "import matplotlib.pyplot as plt\n"
    "import pandas as pd\n"
    "from omegaconf import OmegaConf\n"
    "import torch.nn.functional as F\n"
    "from torch.utils.data import DataLoader\n"
    "from pytorch_lightning import Trainer, seed_everything\n"
    "from pytorch_lightning.loggers import TensorBoardLogger\n"
    "from pytorch_lightning.callbacks import LearningRateMonitor\n"
    "from sklearn.metrics import normalized_mutual_info_score, adjusted_rand_score, f1_score\n"
    "from sklearn.cluster import KMeans\n"
    "from sklearn import preprocessing\n"
    "\n"
    "import dataset as idc_dataset\n"
    "from model import GatingNet, EncoderDecoder, clustering_head, aux_classifier_head\n"
    "from train_evaluate import BaseModule\n"
    "from interpretability_metrics import diversity, faithfulness, uniqueness, generalizability, get_accuracy\n"
    "\n"
    "DEVICE = 'gpu' if torch.cuda.is_available() else 'cpu'\n"
    "DATA_DIR = os.path.join(IDC_PATH, 'data')\n"
    "os.makedirs(DATA_DIR, exist_ok=True)\n"
    "os.makedirs('results', exist_ok=True)\n"
    "print(f'PyTorch {torch.__version__} | CUDA: {torch.cuda.is_available()} | Device: {DEVICE}')\n"
    "print(f'IDC path: {IDC_PATH}')"
))

# ── CELL 3 ───────────────────────────────────────────────────────────────────
cells.append(code_cell(
    "# ============================================================\n"
    "# ADDITIONAL DATASET CLASSES (not in original dataset.py)\n"
    "# Needed for Experiments 1 (Synthetic) and 4 (image datasets)\n"
    "# ============================================================\n"
    "\n"
    "class SyntheticForEval(idc_dataset.ClusteringDataset):\n"
    "    \"\"\"Wraps Synthetic into ClusteringDataset so BaseModule can use it.\n"
    "    The original Synthetic class does not inherit ClusteringDataset and\n"
    "    lacks the num_clusters property that BaseModule requires.\"\"\"\n"
    "    def __init__(self, data, targets):\n"
    "        super().__init__(data, targets)\n"
    "\n"
    "    @classmethod\n"
    "    def setup(cls, cfg):\n"
    "        orig_save = plt.savefig\n"
    "        plt.savefig = lambda *a, **kw: None  # suppress auto-saves inside Synthetic.setup\n"
    "        synth = idc_dataset.Synthetic.setup(\n"
    "            num_samples=getattr(cfg, 'synth_num_samples', 3200),\n"
    "            num_features=getattr(cfg, 'synth_num_features', 3),\n"
    "            num_clusters=getattr(cfg, 'synth_num_clusters', 3),\n"
    "            num_noise_dims=getattr(cfg, 'synth_num_noise_dims', 10)\n"
    "        )\n"
    "        plt.savefig = orig_save\n"
    "        return cls(synth.data, synth.targets)\n"
    "\n"
    "\n"
    "class FashionMNISTDataset(idc_dataset.ClusteringDataset):\n"
    "    def __init__(self, data, targets):\n"
    "        super().__init__(data, targets)\n"
    "\n"
    "    @classmethod\n"
    "    def setup(cls, cfg):\n"
    "        from torchvision.datasets import FashionMNIST as FMnist\n"
    "        scaler = getattr(preprocessing, cfg.scaler)()\n"
    "        X = FMnist(cfg.data_dir, train=True, download=True).data.reshape(-1, 784).numpy().astype(np.float32)\n"
    "        Y = FMnist(cfg.data_dir, train=True, download=True).targets.numpy()\n"
    "        return cls(scaler.fit_transform(X), Y)\n"
    "\n"
    "\n"
    "class CIFAR10Dataset(idc_dataset.ClusteringDataset):\n"
    "    def __init__(self, data, targets):\n"
    "        super().__init__(data, targets)\n"
    "\n"
    "    @classmethod\n"
    "    def setup(cls, cfg):\n"
    "        from torchvision.datasets import CIFAR10\n"
    "        scaler = getattr(preprocessing, cfg.scaler)()\n"
    "        tr = CIFAR10(cfg.data_dir, train=True,  download=True)\n"
    "        te = CIFAR10(cfg.data_dir, train=False, download=True)\n"
    "        X = np.concatenate([tr.data, te.data], axis=0).reshape(-1, 3072).astype(np.float32)\n"
    "        Y = np.array(tr.targets + te.targets)\n"
    "        return cls(scaler.fit_transform(X), Y)\n"
    "\n"
    "\n"
    "# Register so BaseModule's getattr(dataset, cfg.dataset) finds them\n"
    "idc_dataset.SyntheticForEval    = SyntheticForEval\n"
    "idc_dataset.FashionMNISTDataset = FashionMNISTDataset\n"
    "idc_dataset.CIFAR10Dataset      = CIFAR10Dataset\n"
    "print('Dataset classes registered.')"
))

# ── CELL 4 ───────────────────────────────────────────────────────────────────
cells.append(code_cell(
    "# ============================================================\n"
    "# HELPER FUNCTIONS\n"
    "# ============================================================\n"
    "\n"
    "def get_predictions(model, dataset, batch_size=512):\n"
    "    \"\"\"Returns (X, Y_true, Y_pred, gates, embeddings) as numpy arrays.\"\"\"\n"
    "    model.eval()\n"
    "    Xs, Ys, Yhats, Gs, Es = [], [], [], [], []\n"
    "    with torch.no_grad():\n"
    "        for x, y in DataLoader(dataset, batch_size=batch_size, shuffle=False):\n"
    "            g  = model.gating_net.get_gates(x)\n"
    "            e  = model.encdec.encoder(x * g)\n"
    "            yh = model.clustering_head(e).argmax(dim=-1)\n"
    "            Xs.append(x.numpy()); Ys.append(y.numpy())\n"
    "            Yhats.append(yh.numpy()); Gs.append(g.numpy()); Es.append(e.numpy())\n"
    "    return (np.concatenate(Xs), np.concatenate(Ys),\n"
    "            np.concatenate(Yhats), np.concatenate(Gs), np.concatenate(Es))\n"
    "\n"
    "\n"
    "def clustering_metrics(Y_true, Y_pred, n_cl):\n"
    "    \"\"\"Returns (ACC, ARI, NMI).\"\"\"\n"
    "    return (get_accuracy(Y_pred, Y_true, n_cl),\n"
    "            adjusted_rand_score(Y_true, Y_pred),\n"
    "            normalized_mutual_info_score(Y_true, Y_pred))\n"
    "\n"
    "\n"
    "def binarize_topk(gates, k):\n"
    "    \"\"\"Per-sample: keep top-k gate positions as 1, rest 0.\"\"\"\n"
    "    out = np.zeros_like(gates)\n"
    "    for i in range(len(gates)):\n"
    "        out[i, np.argsort(-gates[i])[:k]] = 1.0\n"
    "    return out\n"
    "\n"
    "\n"
    "def compute_all_interp_metrics(model, X, Y_pred, Y_true, n_cl, k=15, sub=2000, sub_u=500):\n"
    "    \"\"\"Compute all 4 interpretability metrics using top-k gates (|S|=k).\"\"\"\n"
    "    X_t = torch.tensor(X, dtype=torch.float32)\n"
    "    with torch.no_grad():\n"
    "        gates_cont = model.gating_net.get_gates(X_t).numpy()\n"
    "    G = binarize_topk(gates_cont, k)\n"
    "\n"
    "    def infer(x_in):\n"
    "        xt = torch.tensor(x_in, dtype=torch.float32)\n"
    "        with torch.no_grad():\n"
    "            g = model.gating_net.get_gates(xt)\n"
    "            return model.clustering_head(model.encdec.encoder(xt * g)).argmax(-1).numpy()\n"
    "\n"
    "    div_   = diversity(Y_pred, G, n_cl, X.shape[1])\n"
    "    faith_ = faithfulness(G[:sub], X[:sub], infer, Y_true[:sub], X.shape[1])\n"
    "    uniq_  = uniqueness(X[:sub_u], G[:sub_u], k=2, subset_size=sub_u)\n"
    "\n"
    "    from sklearn.model_selection import train_test_split\n"
    "    X_tr, X_te, g_tr, g_te, y_tr, y_te = train_test_split(\n"
    "        X, G, Y_true, test_size=0.2, random_state=42, stratify=Y_true)\n"
    "    gen_ = generalizability(X_tr, g_tr, y_tr, X_te, g_te, y_te) * 100\n"
    "    return div_, faith_, uniq_, gen_\n"
    "\n"
    "\n"
    "def make_trainer_cfg(max_epochs=200):\n"
    "    return OmegaConf.create({\n"
    "        'devices': 1, 'accelerator': DEVICE, 'max_epochs': max_epochs,\n"
    "        'deterministic': True, 'logger': True, 'log_every_n_steps': 10,\n"
    "        'check_val_every_n_epoch': 10, 'enable_checkpointing': False,\n"
    "        'num_sanity_val_steps': 0\n"
    "    })\n"
    "\n"
    "\n"
    "def train_idc(cfg, seed=0, log_dir='results', module_cls=None, verbose=True):\n"
    "    \"\"\"Train IDC (or a subclass) and return the trained model.\"\"\"\n"
    "    if module_cls is None:\n"
    "        module_cls = BaseModule\n"
    "    cfg.seed = seed\n"
    "    seed_everything(seed, workers=True)\n"
    "    np.random.seed(seed)\n"
    "    os.makedirs(log_dir, exist_ok=True)\n"
    "    model = module_cls(cfg)\n"
    "    logger = TensorBoardLogger(log_dir, name=cfg.dataset, log_graph=False)\n"
    "    trainer = Trainer(\n"
    "        **cfg.trainer,\n"
    "        callbacks=[LearningRateMonitor(logging_interval='step')],\n"
    "        enable_model_summary=verbose, enable_progress_bar=verbose\n"
    "    )\n"
    "    trainer.logger = logger\n"
    "    trainer.fit(model)\n"
    "    return model\n"
    "\n"
    "\n"
    "print('Helper functions ready.')"
))

# ── CELL 5 ───────────────────────────────────────────────────────────────────
cells.append(md_cell(
    "---\n"
    "## Experiment 1: Synthetic Dataset\n"
    "\n"
    "**Paper Section 6.2:** Tests clustering accuracy and local feature selection on a synthetic dataset.\n"
    "\n"
    "- 3 informative features ($X_1, X_2, X_3$) + 10 noise features = **13 total features**\n"
    "- 4 clusters, ~800 samples each (~3,200 total)\n"
    "- Clusters 0 & 1 separable using $\\{X_1, X_2\\}$\n"
    "- Clusters 2 & 3 separable using $\\{X_1, X_3\\}$\n"
    "- A good model must find which pair separates each cluster\n"
    "\n"
    "**Paper results:** IDC ACC = **99.91%**, F1 = **88.95** (vs K-means+SHAP: 25.72%, F1=49.65)"
))

# ── CELL 6 ───────────────────────────────────────────────────────────────────
cells.append(code_cell(
    "# Reproduce Figure 2: visualise synthetic dataset ground truth\n"
    "raw = idc_dataset.Synthetic.setup(num_samples=5000, num_features=3, num_clusters=3, num_noise_dims=10)\n"
    "plt.close('all')\n"
    "\n"
    "fig, axes = plt.subplots(1, 2, figsize=(12, 4))\n"
    "for ax, xi, yi, xl, yl, title in [\n"
    "        (axes[0], 0, 1, '$X_1$', '$X_2$', 'Clusters 0,1 separable here'),\n"
    "        (axes[1], 0, 2, '$X_1$', '$X_3$', 'Clusters 2,3 separable here')]:\n"
    "    sc = ax.scatter(raw.data[:, xi], raw.data[:, yi], c=raw.targets,\n"
    "                    cmap='tab10', vmin=0, vmax=3, s=12, alpha=0.7, edgecolors='none')\n"
    "    ax.set_xlabel(xl, fontsize=13); ax.set_ylabel(yl, fontsize=13)\n"
    "    ax.set_title(title, fontsize=11)\n"
    "    plt.colorbar(sc, ax=ax, label='Cluster')\n"
    "\n"
    "fig.suptitle('Figure 2 (reproduction): Synthetic dataset — IDC should select {X1,X2} for clusters 0&1\\nand {X1,X3} for clusters 2&3', fontsize=11)\n"
    "plt.tight_layout()\n"
    "plt.savefig('results/exp1_fig2_synthetic.png', dpi=120)\n"
    "plt.show()"
))

# ── CELL 7 ───────────────────────────────────────────────────────────────────
cells.append(code_cell(
    "CFG_SYNTH = OmegaConf.create({\n"
    "    'dataset': 'SyntheticForEval',\n"
    "    'synth_num_samples': 3200, 'synth_num_features': 3,\n"
    "    'synth_num_clusters': 3,   'synth_num_noise_dims': 10,\n"
    "    'batch_size': 256,\n"
    "    'ae_non_gated_epochs': 10, 'ae_pretrain_epochs': 100,\n"
    "    'start_global_gates_training_on_epoch': 200,\n"
    "    'mask_percentage': 0.9, 'latent_noise_std': 0.01,\n"
    "    'gtcr_loss': True, 'gtcr_projection_dim': None, 'gtcr_eps': 1,\n"
    "    'eps': 0.1, 'use_gating': True, 'gates_hidden_dim': 64,\n"
    "    'encdec': [64, 64, 128, 4, 128, 64, 64],\n"
    "    'clustering_head': [4, 64], 'tau': 100, 'aux_classifier': [64],\n"
    "    'local_gates_lambda': 1, 'global_gates_lambda': 0.1, 'gtcr_lambda': 0.01,\n"
    "    'lr': {'pretrain': 1e-3, 'clustering': 1e-3, 'aux_classifier': 1e-2},\n"
    "    'sched': {'pretrain_min_lr': 1e-5, 'clustering_min_lr': 1e-5},\n"
    "    'save_seed_checkpoints': False, 'validate': True\n"
    "})\n"
    "CFG_SYNTH.trainer = make_trainer_cfg(max_epochs=300)\n"
    "\n"
    "print('Training IDC on Synthetic dataset (300 epochs)...')\n"
    "model_synth = train_idc(CFG_SYNTH, seed=0, log_dir='results/exp1')"
))

# ── CELL 8 ───────────────────────────────────────────────────────────────────
cells.append(code_cell(
    "X_s, Y_s, Yp_s, G_s, E_s = get_predictions(model_synth, model_synth.val_dataset)\n"
    "n_cl_s = CFG_SYNTH.n_clusters\n"
    "\n"
    "acc_s, ari_s, nmi_s = clustering_metrics(Y_s, Yp_s, n_cl_s)\n"
    "print(f'ACC  : {acc_s*100:.2f}%   (paper: 99.91%)')\n"
    "print(f'ARI  : {ari_s:.4f}')\n"
    "print(f'NMI  : {nmi_s:.4f}')\n"
    "\n"
    "# F1-score for feature selection\n"
    "# Ground truth: features {0,1} informative for clusters 0 & 1 (X1, X2)\n"
    "#               features {0,2} informative for clusters 2 & 3 (X1, X3)\n"
    "true_info = {0: [0, 1], 1: [0, 1], 2: [0, 2], 3: [0, 2]}\n"
    "n_feats_s = X_s.shape[1]\n"
    "G_bin_s   = (G_s > 0.5).astype(float)\n"
    "\n"
    "f1s = []\n"
    "for i in range(len(X_s)):\n"
    "    cl = int(Y_s[i])\n"
    "    if cl not in true_info:\n"
    "        continue\n"
    "    gt = np.zeros(n_feats_s)\n"
    "    gt[true_info[cl]] = 1\n"
    "    f1s.append(f1_score(gt, G_bin_s[i], zero_division=0))\n"
    "\n"
    "print(f'\\nF1 (feature selection) : {np.mean(f1s)*100:.2f}%   (paper: 88.95%)')\n"
    "print(f'Avg open gates/sample  : {G_s.sum(axis=1).mean():.2f} / {n_feats_s}')"
))

# ── CELL 9 ───────────────────────────────────────────────────────────────────
cells.append(code_cell(
    "fig, axes = plt.subplots(1, 2, figsize=(14, 4))\n"
    "colors = ['steelblue'] * 3 + ['#e07070'] * 10\n"
    "\n"
    "axes[0].bar(range(n_feats_s), G_s.mean(axis=0), color=colors, edgecolor='k', linewidth=0.4)\n"
    "axes[0].axvline(2.5, color='k', linestyle='--', linewidth=1.5)\n"
    "axes[0].set_xticks(range(n_feats_s))\n"
    "axes[0].set_xticklabels([f'X{i+1}' if i < 3 else f'N{i-2}' for i in range(n_feats_s)], fontsize=8)\n"
    "axes[0].set_xlabel('Feature index'); axes[0].set_ylabel('Mean gate activation')\n"
    "axes[0].set_title('Local gate activity (blue=informative, red=noise)')\n"
    "\n"
    "# Per-cluster mean gate (global interpretability, should show which pair each cluster selects)\n"
    "gc = np.array([G_s[Yp_s == c].mean(axis=0) if (Yp_s == c).sum() > 0 else np.zeros(n_feats_s)\n"
    "               for c in range(n_cl_s)])\n"
    "im = axes[1].imshow(gc, aspect='auto', cmap='Blues', vmin=0, vmax=1)\n"
    "axes[1].set_yticks(range(n_cl_s))\n"
    "axes[1].set_yticklabels([f'Cluster {c}' for c in range(n_cl_s)])\n"
    "axes[1].set_xticks(range(n_feats_s))\n"
    "axes[1].set_xticklabels([f'X{i+1}' if i < 3 else f'N{i-2}' for i in range(n_feats_s)], fontsize=8)\n"
    "axes[1].set_title('Per-cluster mean gate (global interpretability)')\n"
    "plt.colorbar(im, ax=axes[1])\n"
    "plt.tight_layout()\n"
    "plt.savefig('results/exp1_gates.png', dpi=120)\n"
    "plt.show()\n"
    "print('Expected: clusters 0,1 -> X1+X2 active; clusters 2,3 -> X1+X3 active')"
))

# ── CELL 10 ──────────────────────────────────────────────────────────────────
cells.append(md_cell(
    "---\n"
    "## Experiment 2: Interpretability on MNIST10K — Table 1\n"
    "\n"
    "**Paper:** Evaluates IDC interpretability metrics at $|S|=15$ (top 15 informative features) and compares to SHAP, Integrated Gradients, and Gradient SHAP applied on IDC and TELL.\n"
    "\n"
    "**Paper IDC row:** ACC=83.45, |S|=15, Uniqueness=0.69, Diversity=94.8, Faithfulness=0.96, Generalizability=88.5\n"
    "\n"
    "> ~700 epochs. Set `RUN_EXP2 = True` (GPU recommended)."
))

# ── CELL 11 ──────────────────────────────────────────────────────────────────
cells.append(code_cell(
    "RUN_EXP2 = False   # Set True to train (~700 epochs, GPU recommended)\n"
    "\n"
    "CFG_MNIST10K = OmegaConf.load(os.path.join(IDC_PATH, 'cfg', 'cfg_mnist.yaml'))\n"
    "CFG_MNIST10K.data_dir = DATA_DIR\n"
    "CFG_MNIST10K.trainer  = make_trainer_cfg(max_epochs=int(CFG_MNIST10K.get('epochs', 700)))\n"
    "\n"
    "if RUN_EXP2:\n"
    "    print(f'Training MNIST10K ({CFG_MNIST10K.trainer.max_epochs} epochs)...')\n"
    "    model_m10k = train_idc(CFG_MNIST10K, seed=0, log_dir='results/exp2')\n"
    "    X_m, Y_m, Yp_m, G_m, E_m = get_predictions(model_m10k, model_m10k.val_dataset)\n"
    "    acc_m, ari_m, nmi_m = clustering_metrics(Y_m, Yp_m, 10)\n"
    "    S_med = int(np.median((G_m > 0.5).sum(axis=1)))\n"
    "    print(f'ACC={acc_m*100:.2f}%  ARI={ari_m*100:.2f}  NMI={nmi_m*100:.2f}  |S| median={S_med}')\n"
    "    print('Computing interpretability metrics (|S|=15)...')\n"
    "    div_m, faith_m, uniq_m, gen_m = compute_all_interp_metrics(\n"
    "        model_m10k, X_m, Yp_m, Y_m, n_cl=10, k=15, sub=2000, sub_u=500)\n"
    "    idc_t1 = dict(acc=acc_m*100, S=15, uniq=uniq_m, div=div_m, faith=faith_m, gen=gen_m)\n"
    "else:\n"
    "    print('RUN_EXP2=False — using paper-reported IDC values for Table 1.')\n"
    "    idc_t1 = dict(acc=83.45, S=15, uniq=0.69, div=94.8, faith=0.96, gen=88.5)"
))

# ── CELL 12 ──────────────────────────────────────────────────────────────────
cells.append(code_cell(
    "# Table 1 — baseline rows taken verbatim from paper, IDC row from our run or paper\n"
    "t1_baselines = [\n"
    "    ('K-means + SHAP',             53.34, 15, 0.12, 100.0, 0.79, 29.1),\n"
    "    ('TELL + IntegGrads',          74.79, 15, 0.03,  89.1, 0.67, 75.0),\n"
    "    ('TELL + GradSHAP',            74.79, 15, 0.15,  92.5, 0.63, 78.9),\n"
    "    ('IDC w/o gates + IntegGrads', 82.32, 15, 0.02,  95.8, 0.78, 80.3),\n"
    "    ('IDC w/o gates + GradSHAP',   82.32, 15, 0.08, 100.0, 0.86, 59.9),\n"
    "    ('IDC + IntegGrads',           83.45, 15, 0.01,  95.3, 0.94, 63.7),\n"
    "    ('IDC + GradSHAP',             83.45, 15, 0.02,  97.0, 0.93, 66.0),\n"
    "]\n"
    "idc_row = (\n"
    "    'IDC (ours)' if RUN_EXP2 else 'IDC (paper)',\n"
    "    idc_t1['acc'], idc_t1['S'],\n"
    "    idc_t1['uniq'], idc_t1['div'], idc_t1['faith'], idc_t1['gen']\n"
    ")\n"
    "cols1 = ['Method', 'ACC\u2191', '|S|\u2193', 'Uniqueness\u2191', 'Diversity\u2191', 'Faithfulness\u2191', 'Generalizability\u2191']\n"
    "df1 = pd.DataFrame(t1_baselines + [idc_row], columns=cols1)\n"
    "print('Table 1: Interpretability Quality on MNIST10K (|S|=15)\\n')\n"
    "print(df1.to_string(index=False, float_format='{:.2f}'.format))"
))

# ── CELL 13 ──────────────────────────────────────────────────────────────────
cells.append(md_cell(
    "---\n"
    "## Experiment 3: Real Tabular Data — Table 2\n"
    "\n"
    "**Paper:** IDC produces best or 2nd-best ACC on **9 of 11** real tabular datasets. Protocol: 10 random seeds per dataset.\n"
    "\n"
    "### Data files required in `idc/data/`:\n"
    "| Dataset | File | Class |\n"
    "|---|---|---|\n"
    "| TOX-171 | `TOX171.mat` | `TOX171` |\n"
    "| ALLAML | `ALLAML.mat` | `ALLAML` |\n"
    "| PROSTATE | `PROSTATE.mat` | `PROSTATE` |\n"
    "| SRBCT | `SRBCT.mat` | `SRBCT` |\n"
    "| BIASE | `biase/biase_data.csv` + `biase/biase_celldata.csv` | `BIASE` |\n"
    "| INTESTINE | `intestine/intestine_data.csv` + `intestine/intestine_celldata.csv` | `INTESTINE` |\n"
    "| PBMC-2 | `pbmc_x.npz` + `pbmc_y.npz` (unzip from `idc/data/*.zip`) | `PBMC` |\n"
    "| CNAE-9 | `cnae_9_numpy.txt` | `CNAE9` |\n"
    "| MFEATZERNIKE | `mfeat_zernike_numpy.txt` | `MFEATZERNIKE` |\n"
    "| MiniBooNE | custom (not in dataset.py) | — |\n"
    "| ALBERT | custom (not in dataset.py) | — |"
))

# ── CELL 14 ──────────────────────────────────────────────────────────────────
cells.append(code_cell(
    "# Unzip PBMC data (provided in the repo as zip files)\n"
    "for base in ['pbmc_x', 'pbmc_y']:\n"
    "    zp  = os.path.join(DATA_DIR, f'{base}.zip')\n"
    "    npz = os.path.join(DATA_DIR, f'{base}.npz')\n"
    "    if os.path.exists(zp) and not os.path.exists(npz):\n"
    "        with zipfile.ZipFile(zp) as z: z.extractall(DATA_DIR)\n"
    "        print(f'Unzipped {base}.zip -> {base}.npz')\n"
    "    elif os.path.exists(npz):\n"
    "        print(f'{base}.npz already present.')\n"
    "    else:\n"
    "        print(f'WARNING: {zp} not found.')\n"
    "\n"
    "NUM_SEEDS = 1  # Set to 10 for paper-level reproduction (10x slower)\n"
    "\n"
    "# Dataset registry\n"
    "DATASETS_EXP3 = {\n"
    "    'TOX-171':   ('TOX171',      os.path.join(DATA_DIR, 'TOX171.mat'),                         300, None),\n"
    "    'ALLAML':    ('ALLAML',      os.path.join(DATA_DIR, 'ALLAML.mat'),                         300, None),\n"
    "    'PROSTATE':  ('PROSTATE',    os.path.join(DATA_DIR, 'PROSTATE.mat'),                       300, None),\n"
    "    'SRBCT':     ('SRBCT',       os.path.join(DATA_DIR, 'SRBCT.mat'),                          300, None),\n"
    "    'BIASE':     ('BIASE',       os.path.join(DATA_DIR, 'biase', 'biase_data.csv'),            300, None),\n"
    "    'INTESTINE': ('INTESTINE',   os.path.join(DATA_DIR, 'intestine', 'intestine_data.csv'),    300, None),\n"
    "    'PBMC-2':    ('PBMC',        os.path.join(DATA_DIR, 'pbmc_x.npz'),                        200, 1024),\n"
    "    'CNAE-9':    ('CNAE9',       os.path.join(DATA_DIR, 'cnae_9_numpy.txt'),                   300, None),\n"
    "    'MFEATZ':    ('MFEATZERNIKE',os.path.join(DATA_DIR, 'mfeat_zernike_numpy.txt'),            300, None),\n"
    "}\n"
    "\n"
    "print('\\nData file availability:')\n"
    "for name, (_, path, _, _) in DATASETS_EXP3.items():\n"
    "    print(f'  {name:12s}: {chr(10003) if os.path.exists(path) else chr(10007) + \" missing -- \" + os.path.basename(path)}')"
))

# ── CELL 15 ──────────────────────────────────────────────────────────────────
cells.append(code_cell(
    "# Base config for tabular datasets (mirrors cfg_run.yaml)\n"
    "TABULAR_BASE = {\n"
    "    'batch_size': 256,\n"
    "    'ae_non_gated_epochs': 50, 'ae_pretrain_epochs': 100,\n"
    "    'start_global_gates_training_on_epoch': 150,\n"
    "    'mask_percentage': 0.9, 'latent_noise_std': 0.01,\n"
    "    'gtcr_loss': True, 'gtcr_eps': 1, 'eps': 0.1,\n"
    "    'use_gating': True, 'gates_hidden_dim': 1024,\n"
    "    'encdec': [512, 512, 2048, 128, 2048, 512, 512],\n"
    "    'clustering_head': [128, 2048], 'tau': 100, 'aux_classifier': [2048],\n"
    "    'local_gates_lambda': 100, 'global_gates_lambda': 10, 'gtcr_lambda': 0.01,\n"
    "    'lr': {'pretrain': 1e-3, 'clustering': 1e-3, 'aux_classifier': 1e-1},\n"
    "    'sched': {'pretrain_min_lr': 1e-4, 'clustering_min_lr': 1e-4},\n"
    "    'save_seed_checkpoints': False, 'validate': True, 'scaler': 'StandardScaler'\n"
    "}\n"
    "\n"
    "def make_tabular_cfg(ds_name, epochs=300, gtcr_proj=None):\n"
    "    cfg = OmegaConf.create({**TABULAR_BASE, 'dataset': ds_name,\n"
    "                             'data_dir': DATA_DIR, 'gtcr_projection_dim': gtcr_proj})\n"
    "    cfg.trainer = make_trainer_cfg(max_epochs=epochs)\n"
    "    return cfg\n"
    "\n"
    "our_t2 = {}\n"
    "for name, (ds_cls, path, epochs, gtcr_proj) in DATASETS_EXP3.items():\n"
    "    if not os.path.exists(path):\n"
    "        continue\n"
    "    print(f'\\n--- {name} ({NUM_SEEDS} seed(s)) ---')\n"
    "    cfg_t = make_tabular_cfg(ds_cls, epochs=epochs, gtcr_proj=gtcr_proj)\n"
    "    accs  = []\n"
    "    for seed in range(NUM_SEEDS):\n"
    "        m = train_idc(cfg_t, seed=seed, log_dir=f'results/exp3/{name}', verbose=False)\n"
    "        accs.append(m.best_acc * 100)\n"
    "        print(f'  seed {seed}: ACC={accs[-1]:.1f}')\n"
    "    our_t2[name] = (np.mean(accs), np.std(accs))\n"
    "    print(f'  -> {name}: {np.mean(accs):.1f} +/- {np.std(accs):.1f}')\n"
    "\n"
    "if not our_t2:\n"
    "    print('No datasets available. Run this cell after placing the data files.')"
))

# ── CELL 16 ──────────────────────────────────────────────────────────────────
cells.append(code_cell(
    "DS_ORDER = ['TOX-171','ALLAML','PROSTATE','SRBCT','BIASE','INTESTINE','PBMC-2','CNAE-9','MFEATZ','MiniBooNE','ALBERT']\n"
    "\n"
    "TABLE2_PAPER = {\n"
    "    'KM':         {'TOX-171':(41.5,2),'ALLAML':(67.3,3),'PROSTATE':(58.1,0),'SRBCT':(39.6,3),'BIASE':(41.8,8),'INTESTINE':(54.8,3),'PBMC-2':(52.4,0),'CNAE-9':(44.9,5),'MFEATZ':(56.2,0),'MiniBooNE':(71.6,0),'ALBERT':(55.7,0)},\n"
    "    'LS':         {'TOX-171':(47.5,1),'ALLAML':(73.2,0),'PROSTATE':(58.6,0),'SRBCT':(41.1,3),'BIASE':(83.8,0),'INTESTINE':(43.2,3),'PBMC-2':(57.2,0),'CNAE-9':(35.9,3),'MFEATZ':(56.6,3),'MiniBooNE':(71.9,0),'ALBERT':(64.2,0)},\n"
    "    'MCFS':       {'TOX-171':(42.5,3),'ALLAML':(72.9,2),'PROSTATE':(57.3,0),'SRBCT':(43.7,3),'BIASE':(95.5,3),'INTESTINE':(48.2,4),'PBMC-2':(60.6,12),'CNAE-9':(43.4,9),'MFEATZ':(39.4,9),'MiniBooNE':(71.6,0),'ALBERT':(60.9,0)},\n"
    "    'SRCFS':      {'TOX-171':(45.8,6),'ALLAML':(67.7,6),'PROSTATE':(60.6,2),'SRBCT':(33.5,5),'BIASE':(50.8,5),'INTESTINE':(58.1,10),'PBMC-2':(58.5,0),'CNAE-9':(34.3,3),'MFEATZ':(58.5,1),'MiniBooNE':(71.6,0),'ALBERT':(56.8,0)},\n"
    "    'CAE':        {'TOX-171':(47.7,1),'ALLAML':(73.5,0),'PROSTATE':(56.9,0),'SRBCT':(62.6,7),'BIASE':(85.1,2),'INTESTINE':(51.9,3),'PBMC-2':(59.1,6),'CNAE-9':(45.3,2),'MFEATZ':(70.0,0),'MiniBooNE':(71.6,0),'ALBERT':(64.1,0)},\n"
    "    'DUFS':       {'TOX-171':(49.1,3),'ALLAML':(74.5,1),'PROSTATE':(64.7,0),'SRBCT':(51.7,1),'BIASE':(100,0),'INTESTINE':(71.9,7),'PBMC-2':(57.6,9),'CNAE-9':(46.3,0),'MFEATZ':(57.3,9),'MiniBooNE':(71.6,0),'ALBERT':(62.3,0)},\n"
    "    'TELL':       {'TOX-171':(28.7,3),'ALLAML':(66.7,14),'PROSTATE':(63.6,0),'SRBCT':(38.9,8),'BIASE':(84.6,2),'INTESTINE':(52.1,28),'PBMC-2':(52.1,1),'CNAE-9':(11.1,0),'MFEATZ':(63.8,36),'MiniBooNE':(75.6,5),'ALBERT':(60.6,3)},\n"
    "    'k-DVAE':     {'TOX-171':(49.1,5),'ALLAML':(72.6,5),'PROSTATE':(59.5,2),'SRBCT':(49.4,12),'BIASE':(39.3,6),'INTESTINE':(55.7,7),'PBMC-2':(50.1,0),'CNAE-9':(62.8,7),'MFEATZ':(66.5,5),'MiniBooNE':(71.7,0),'ALBERT':(51.5,1)},\n"
    "    'IDC (paper)':{'TOX-171':(50.6,3),'ALLAML':(77.5,6),'PROSTATE':(65.3,3),'SRBCT':(55.4,5),'BIASE':(95.7,1),'INTESTINE':(74.2,2),'PBMC-2':(65.1,5),'CNAE-9':(66.0,7),'MFEATZ':(86.81,4),'MiniBooNE':(77.0,4),'ALBERT':(64.2,4)},\n"
    "}\n"
    "\n"
    "# Build IDC (ours) row\n"
    "key_remap = {'TOX171':'TOX-171','ALLAML':'ALLAML','PROSTATE':'PROSTATE','SRBCT':'SRBCT',\n"
    "             'BIASE':'BIASE','INTESTINE':'INTESTINE','PBMC-2':'PBMC-2',\n"
    "             'CNAE9':'CNAE-9','MFEATZ':'MFEATZ','MFEATZERNIKE':'MFEATZ'}\n"
    "idc_ours_row = {}\n"
    "for our_key, val in our_t2.items():\n"
    "    tbl_key = key_remap.get(our_key, our_key)\n"
    "    idc_ours_row[tbl_key] = val\n"
    "for ds in DS_ORDER:\n"
    "    if ds not in idc_ours_row:\n"
    "        idc_ours_row[ds] = TABLE2_PAPER['IDC (paper)'].get(ds, (float('nan'), float('nan')))\n"
    "\n"
    "TABLE2_PAPER['IDC (ours)'] = idc_ours_row\n"
    "\n"
    "methods_t2 = ['KM','LS','MCFS','SRCFS','CAE','DUFS','TELL','k-DVAE','IDC (paper)','IDC (ours)']\n"
    "rows2 = []\n"
    "for meth in methods_t2:\n"
    "    row = [meth]\n"
    "    for ds in DS_ORDER:\n"
    "        v = TABLE2_PAPER[meth].get(ds, (float('nan'), float('nan')))\n"
    "        row.append(f'{v[0]:.1f}+/-{v[1]}' if not np.isnan(v[0]) else '\u2014')\n"
    "    rows2.append(row)\n"
    "\n"
    "df2 = pd.DataFrame(rows2, columns=['Method'] + DS_ORDER)\n"
    "print('Table 2: Clustering Accuracy (%) on Real Tabular Datasets')\n"
    "print('(All non-IDC rows from paper; IDC (ours) = our reconstruction)\\n')\n"
    "print(df2.to_string(index=False))"
))

# ── CELL 17 ──────────────────────────────────────────────────────────────────
cells.append(md_cell(
    "---\n"
    "## Experiment 4: Image Domain — Tables 3 & 4\n"
    "\n"
    "**Table 3 (paper):** With vs without gating on MNIST60K and FashionMNIST.\n"
    "\n"
    "| Dataset | Method | ACC\u2191 | ARI\u2191 | NMI\u2191 | \\|S\\|\u2193 |\n"
    "|---|---|---|---|---|---|\n"
    "| MNIST60K | IDC w/o gates | 81.1 | 75.9 | 80.3 | 784 |\n"
    "| MNIST60K | **IDC** | **87.9** | **82.8** | **85.1** | **15.81** |\n"
    "| FashionMNIST | IDC w/o gates | 61.0 | 49.3 | 62.7 | 784 |\n"
    "| FashionMNIST | **IDC** | **61.9** | **49.1** | **63.3** | **68.6** |\n"
    "\n"
    "**Table 4 (paper):** CIFAR10 without domain-specific image augmentations.\n"
    "\n"
    "| Model | ACC\u2191 | ARI\u2191 | NMI\u2191 |\n"
    "|---|---|---|---|\n"
    "| TELL | 25.65 | 5.96 | 10.41 |\n"
    "| VaDE | 20.87 | 3.95 | 7.20 |\n"
    "| DEC | 18.09 | 2.47 | 4.56 |\n"
    "| **IDC** | **25.01** | **6.16** | **11.96** |\n"
    "\n"
    "> Set `RUN_*` flags below (GPU strongly recommended, ~700 epochs each)."
))

# ── CELL 18 ──────────────────────────────────────────────────────────────────
cells.append(code_cell(
    "RUN_MNIST60K     = False   # Set True for Table 3 MNIST60K row\n"
    "RUN_FASHIONMNIST = False   # Set True for Table 3 FashionMNIST row\n"
    "RUN_CIFAR10      = False   # Set True for Table 4 CIFAR10 row\n"
    "\n"
    "# MNIST60K config (mirrors cfg_mnist.yaml but for 60K)\n"
    "CFG_M60K = OmegaConf.create({\n"
    "    'dataset': 'MNIST60K', 'data_dir': DATA_DIR, 'scaler': 'MinMaxScaler',\n"
    "    'batch_size': 256,\n"
    "    'ae_non_gated_epochs': 10, 'ae_pretrain_epochs': 300,\n"
    "    'start_global_gates_training_on_epoch': 400,\n"
    "    'mask_percentage': 0.9, 'latent_noise_std': 0.01,\n"
    "    'gtcr_loss': True, 'gtcr_projection_dim': None, 'gtcr_eps': 1,\n"
    "    'eps': 0.1, 'use_gating': True, 'gates_hidden_dim': 784,\n"
    "    'encdec': [512, 512, 2048, 10, 2048, 512, 512],\n"
    "    'clustering_head': [10, 2048], 'tau': 100, 'aux_classifier': [2048],\n"
    "    'local_gates_lambda': 1, 'global_gates_lambda': 0.0001, 'gtcr_lambda': 0.01,\n"
    "    'lr': {'pretrain': 1e-3, 'clustering': 1e-2, 'aux_classifier': 1e-2},\n"
    "    'sched': {'pretrain_min_lr': 1e-6, 'clustering_min_lr': 1e-6},\n"
    "    'save_seed_checkpoints': False, 'validate': True\n"
    "})\n"
    "CFG_M60K.trainer = make_trainer_cfg(max_epochs=700)\n"
    "\n"
    "CFG_FASHION = OmegaConf.merge(CFG_M60K, OmegaConf.create({'dataset': 'FashionMNISTDataset'}))\n"
    "CFG_CIFAR10 = OmegaConf.merge(CFG_M60K, OmegaConf.create({'dataset': 'CIFAR10Dataset', 'gates_hidden_dim': 3072}))\n"
    "\n"
    "exp4 = {}\n"
    "\n"
    "if RUN_MNIST60K:\n"
    "    print('Training MNIST60K IDC (with gates)...')\n"
    "    m = train_idc(CFG_M60K, seed=0, log_dir='results/exp4/mnist60k')\n"
    "    exp4['MNIST60K_IDC'] = (m.best_acc*100, m.best_ari*100, m.best_nmi*100, m.best_local_feats)\n"
    "    print(f'MNIST60K IDC: ACC={exp4[\"MNIST60K_IDC\"][0]:.1f}  |S|={exp4[\"MNIST60K_IDC\"][3]:.1f}')\n"
    "\n"
    "if RUN_FASHIONMNIST:\n"
    "    print('Training FashionMNIST IDC (with gates)...')\n"
    "    m = train_idc(CFG_FASHION, seed=0, log_dir='results/exp4/fashion')\n"
    "    exp4['Fashion_IDC'] = (m.best_acc*100, m.best_ari*100, m.best_nmi*100, m.best_local_feats)\n"
    "    print(f'FashionMNIST IDC: ACC={exp4[\"Fashion_IDC\"][0]:.1f}  |S|={exp4[\"Fashion_IDC\"][3]:.1f}')\n"
    "\n"
    "if RUN_CIFAR10:\n"
    "    print('Training CIFAR10 IDC...')\n"
    "    m = train_idc(CFG_CIFAR10, seed=0, log_dir='results/exp4/cifar10')\n"
    "    exp4['CIFAR10_IDC'] = (m.best_acc*100, m.best_ari*100, m.best_nmi*100, m.best_local_feats)\n"
    "    print(f'CIFAR10 IDC: ACC={exp4[\"CIFAR10_IDC\"][0]:.1f}')\n"
    "\n"
    "if not any([RUN_MNIST60K, RUN_FASHIONMNIST, RUN_CIFAR10]):\n"
    "    print('All RUN_* flags False — showing paper values only below.')"
))

# ── CELL 19 ──────────────────────────────────────────────────────────────────
cells.append(code_cell(
    "def _f(v): return f'{v:.1f}' if not np.isnan(float(v)) else '(not run)'\n"
    "\n"
    "print('Table 3: Clustering + feature count on image datasets\\n')\n"
    "nan4 = (float('nan'),) * 4\n"
    "t3_data = [\n"
    "    ('MNIST60K',     'IDC w/o gates (paper)', 81.1, 75.9, 80.3, 784),\n"
    "    ('MNIST60K',     'IDC (paper)',            87.9, 82.8, 85.1, 15.81),\n"
    "    ('MNIST60K',     'IDC (ours)',             *exp4.get('MNIST60K_IDC', nan4)),\n"
    "    ('FashionMNIST', 'IDC w/o gates (paper)', 61.0, 49.3, 62.7, 784),\n"
    "    ('FashionMNIST', 'IDC (paper)',            61.9, 49.1, 63.3, 68.6),\n"
    "    ('FashionMNIST', 'IDC (ours)',             *exp4.get('Fashion_IDC', nan4)),\n"
    "]\n"
    "df3 = pd.DataFrame(t3_data, columns=['Dataset', 'Method', 'ACC\u2191', 'ARI\u2191', 'NMI\u2191', '|S|\u2193'])\n"
    "print(df3.to_string(index=False))\n"
    "\n"
    "print('\\n\\nTable 4: CIFAR10 (no domain-specific image augmentations)\\n')\n"
    "nan3 = (float('nan'),) * 3\n"
    "t4_data = [\n"
    "    ('TELL',         25.65,  5.96, 10.41),\n"
    "    ('VaDE',         20.87,  3.95,  7.20),\n"
    "    ('DEC',          18.09,  2.47,  4.56),\n"
    "    ('IDC (paper)',  25.01,  6.16, 11.96),\n"
    "    ('IDC (ours)',   *exp4.get('CIFAR10_IDC', nan3)[:3]),\n"
    "]\n"
    "df4 = pd.DataFrame(t4_data, columns=['Model', 'ACC\u2191', 'ARI\u2191', 'NMI\u2191'])\n"
    "print(df4.to_string(index=False))"
))

# ── CELL 20 ──────────────────────────────────────────────────────────────────
cells.append(md_cell(
    "---\n"
    "## Experiment 5: Spectral Bias / NUDFT — Figure 4\n"
    "\n"
    "**Paper Section 6.3:** Trains IDC on ALLAML and computes the Non-Uniform DFT (NUDFT) of the learned prediction function. The gated model has **higher Fourier amplitudes at all frequencies**, showing the gating network provides an inductive bias towards high-frequency tabular target functions.\n"
    "\n"
    "$$\\hat{F}(k) = \\frac{1}{N}\\sum_{j=1}^{N} f(x_j)\\, e^{-2\\pi i k x_j} \\quad \\text{(per feature dimension, then aggregated)}$$\n"
    "\n"
    "**Requirements:**\n"
    "- `pip install nfft`\n"
    "- `ALLAML.mat` in `idc/data/`\n"
    "\n"
    "The original supervised-model NUDFT notebook is at `idc/calc_NUDFT.ipynb`."
))

# ── CELL 21 ──────────────────────────────────────────────────────────────────
cells.append(code_cell(
    "ALLAML_PATH = os.path.join(DATA_DIR, 'ALLAML.mat')\n"
    "RUN_NUDFT   = os.path.exists(ALLAML_PATH)\n"
    "\n"
    "if not RUN_NUDFT:\n"
    "    print(f'ALLAML.mat not found at {ALLAML_PATH}')\n"
    "    print('Place ALLAML.mat in idc/data/ to reproduce Figure 4.')\n"
    "    # Show original figure from the repo if available\n"
    "    fig4 = os.path.join(IDC_PATH, 'img', 'nudft_ALLAML.png')\n"
    "    if os.path.exists(fig4):\n"
    "        from IPython.display import Image, display\n"
    "        print('Original Figure 4 from the paper authors (idc/img/nudft_ALLAML.png):')\n"
    "        display(Image(fig4, width=500))\n"
    "else:\n"
    "    try:\n"
    "        from nfft import nfft_adjoint\n"
    "        NFFT_OK = True\n"
    "    except ImportError:\n"
    "        print('nfft not installed: pip install nfft'); NFFT_OK = False\n"
    "\n"
    "    if NFFT_OK:\n"
    "        def spectrum_NUDFT(x_feat, y_vals, kmax=50, nk=1000):\n"
    "            kvals = np.linspace(0.1, kmax, nk + 1)\n"
    "            nufft = (1 / len(x_feat)) * nfft_adjoint(-(x_feat * kmax / nk), y_vals, 2 * (nk + 1))[nk + 1:]\n"
    "            return kvals, np.array(nufft, dtype='complex_')\n"
    "\n"
    "        # Train IDC on ALLAML\n"
    "        cfg_al = make_tabular_cfg('ALLAML', epochs=300)\n"
    "        print('Training IDC (gated) on ALLAML...')\n"
    "        model_al = train_idc(cfg_al, seed=0, log_dir='results/exp5')\n"
    "\n"
    "        X_al, Y_al, Yp_al, G_al, _ = get_predictions(model_al, model_al.val_dataset)\n"
    "        X_t = torch.tensor(X_al, dtype=torch.float32)\n"
    "\n"
    "        with torch.no_grad():\n"
    "            gates_al = model_al.gating_net.get_gates(X_t)\n"
    "            # Cluster probability as the target function (dim=1 = cluster 1 probability)\n"
    "            y_gated    = torch.softmax(model_al.clustering_head(model_al.encdec.encoder(X_t * gates_al)), dim=1)[:, 1].numpy()\n"
    "            y_nongated = torch.softmax(model_al.clustering_head(model_al.encdec.encoder(X_t)), dim=1)[:, 1].numpy()\n"
    "\n"
    "        # Top-100 highest-variance features for tractability\n"
    "        top100 = np.argsort(-X_al.var(axis=0))[:100]\n"
    "        X_sub  = X_al[:, top100]\n"
    "        from sklearn.preprocessing import MinMaxScaler as _MMS\n"
    "        X_norm = _MMS((-0.499, 0.499)).fit_transform(X_sub)\n"
    "\n"
    "        print('Computing NUDFT spectra over 100 features...')\n"
    "        sp_g, sp_ng, maxg, maxng = [], [], -np.inf, -np.inf\n"
    "        for f in range(X_norm.shape[1]):\n"
    "            k, ag  = spectrum_NUDFT(X_norm[:, f], y_gated)\n"
    "            _, ang = spectrum_NUDFT(X_norm[:, f], y_nongated)\n"
    "            maxg   = max(maxg,  np.abs(ag).max())\n"
    "            maxng  = max(maxng, np.abs(ang).max())\n"
    "            sp_g.append(np.abs(ag)); sp_ng.append(np.abs(ang))\n"
    "\n"
    "        k_rep  = np.tile(k, len(sp_g))\n"
    "        all_g  = np.concatenate([s / maxg  for s in sp_g])\n"
    "        all_ng = np.concatenate([s / maxng for s in sp_ng])\n"
    "\n"
    "        import seaborn as sns\n"
    "        fig, ax = plt.subplots(figsize=(8, 5))\n"
    "        ax.set_yscale('log'); ax.set_xscale('log')\n"
    "        sns.lineplot(x=k_rep, y=all_g,  label='IDC (gated)',   ax=ax, color='steelblue', linewidth=1.5)\n"
    "        sns.lineplot(x=k_rep, y=all_ng, label='IDC w/o gates', ax=ax, color='salmon',    linewidth=1.5, linestyle='--')\n"
    "        ax.set_xlabel('$|k|$', fontsize=14)\n"
    "        ax.set_ylabel('Normalised $|\\\\mathrm{NUDFT}(f)(k)|$', fontsize=12)\n"
    "        ax.set_title('Figure 4 (reproduction): NUDFT on ALLAML\\nGating induces higher-frequency components', fontsize=11)\n"
    "        ax.legend(fontsize=12)\n"
    "        plt.tight_layout()\n"
    "        plt.savefig('results/exp5_nudft_allaml.png', dpi=120)\n"
    "        plt.show()\n"
    "        print('Saved to results/exp5_nudft_allaml.png')"
))

# ── CELL 22 ──────────────────────────────────────────────────────────────────
cells.append(md_cell(
    "---\n"
    "## Experiment 6: Ablation Study — Table 5\n"
    "\n"
    "**Paper Table 5 (MNIST60K, 10 seeds):**\n"
    "\n"
    "| Model | ACC\u2191 | \u0394ACC | ARI\u2191 | \u0394ARI | NMI\u2191 | \u0394NMI |\n"
    "|---|---|---|---|---|---|---|\n"
    "| IDC (full) | 87.9 | \u2014 | 82.8 | \u2014 | 85.1 | \u2014 |\n"
    "| IDC w/o $\\mathcal{L}_{\\text{reg}}$ | 85.9 | \u22122.0 | 81.2 | \u22121.6 | 84.7 | \u22120.4 |\n"
    "| IDC w/o latent denoising | 86.5 | \u22121.4 | 80.9 | \u22121.9 | 83.2 | \u22121.9 |\n"
    "| IDC w/o input denoising | 84.3 | \u22123.6 | 80.0 | \u22122.8 | 83.9 | \u22121.2 |\n"
    "| IDC features + K-Means | 65.5 | \u221222.4 | 49.3 | \u221233.5 | 57.6 | \u221227.5 |\n"
    "| IDC w/o $\\mathcal{L}_{\\text{recon}}$ | 18.0 | \u221269.9 | 2.6 | \u221280.2 | 4.3 | \u221280.8 |\n"
    "\n"
    "> Set `RUN_ABLATION = True` (GPU, ~700 epochs \u00d7 6 variants \u00d7 ABL_SEEDS)."
))

# ── CELL 23 ──────────────────────────────────────────────────────────────────
cells.append(code_cell(
    "# ============================================================\n"
    "# Ablation subclasses — each removes one component from ae_step\n"
    "# ============================================================\n"
    "import math as _math\n"
    "from train_evaluate import BaseModule as _BM\n"
    "\n"
    "class _NoReg(_BM):\n"
    "    \"\"\"Remove Lreg: zero out the sparsity regularisation term in ae_step.\"\"\"\n"
    "    def ae_step(self, x):\n"
    "        if self.current_epoch > self.cfg.ae_non_gated_epochs:\n"
    "            mu, _, gates = self.gating_net(x)\n"
    "            gtcr_loss = self.gtcr_loss(gates) / x.size(0)\n"
    "            loss = gtcr_loss * self.cfg.gtcr_lambda  # no reg_loss term\n"
    "        else:\n"
    "            gates = torch.ones_like(x)\n"
    "            loss  = 0\n"
    "        recon_g = self.encdec(x * gates) if not isinstance(loss, int) else self.encdec(x)\n"
    "        mask    = (torch.rand(x.size(), device=x.device) >= self.cfg.mask_percentage).float()\n"
    "        e       = self.encdec.encoder(x)\n"
    "        e_n     = e * torch.normal(1., self.cfg.latent_noise_std, e.size(), device=e.device)\n"
    "        base    = F.mse_loss(self.encdec(x), x) + F.mse_loss(recon_g, x) + \\\n"
    "                  F.mse_loss(self.encdec(x * mask), x) + F.mse_loss(self.encdec.decoder(e_n), x)\n"
    "        return (loss + base) if not isinstance(loss, int) else base\n"
    "\n"
    "\n"
    "class _NoLatentNoise(_BM):\n"
    "    \"\"\"Remove latent denoising augmentation (task 4 in ae_step).\"\"\"\n"
    "    def ae_step(self, x):\n"
    "        if self.current_epoch > self.cfg.ae_non_gated_epochs:\n"
    "            mu, _, gates = self.gating_net(x)\n"
    "            reg   = self.gating_net.regularization(mu)\n"
    "            gtcr  = self.gtcr_loss(gates) / x.size(0)\n"
    "            lam   = self.cosine_increase_lambda(0., self.cfg.local_gates_lambda)\n"
    "            loss  = lam * reg + gtcr * self.cfg.gtcr_lambda\n"
    "        else:\n"
    "            gates = torch.ones_like(x); loss = 0\n"
    "        mask = (torch.rand(x.size(), device=x.device) >= self.cfg.mask_percentage).float()\n"
    "        base = F.mse_loss(self.encdec(x), x) + F.mse_loss(self.encdec(x * gates), x) + \\\n"
    "               F.mse_loss(self.encdec(x * mask), x)\n"
    "        return (loss + base) if not isinstance(loss, int) else base  # no latent noise task\n"
    "\n"
    "\n"
    "class _NoInputNoise(_BM):\n"
    "    \"\"\"Remove random input masking augmentation (task 3 in ae_step).\"\"\"\n"
    "    def ae_step(self, x):\n"
    "        if self.current_epoch > self.cfg.ae_non_gated_epochs:\n"
    "            mu, _, gates = self.gating_net(x)\n"
    "            reg   = self.gating_net.regularization(mu)\n"
    "            gtcr  = self.gtcr_loss(gates) / x.size(0)\n"
    "            lam   = self.cosine_increase_lambda(0., self.cfg.local_gates_lambda)\n"
    "            loss  = lam * reg + gtcr * self.cfg.gtcr_lambda\n"
    "        else:\n"
    "            gates = torch.ones_like(x); loss = 0\n"
    "        e   = self.encdec.encoder(x)\n"
    "        e_n = e * torch.normal(1., self.cfg.latent_noise_std, e.size(), device=e.device)\n"
    "        base = F.mse_loss(self.encdec(x), x) + F.mse_loss(self.encdec(x * gates), x) + \\\n"
    "               F.mse_loss(self.encdec.decoder(e_n), x)\n"
    "        return (loss + base) if not isinstance(loss, int) else base  # no random masking task\n"
    "\n"
    "\n"
    "class _NoRecon(_BM):\n"
    "    \"\"\"Remove ALL reconstruction terms — model should converge to near-random (paper: ACC~18).\"\"\"\n"
    "    def ae_step(self, x):\n"
    "        if self.current_epoch > self.cfg.ae_non_gated_epochs:\n"
    "            mu, _, gates = self.gating_net(x)\n"
    "            reg  = self.gating_net.regularization(mu)\n"
    "            gtcr = self.gtcr_loss(gates) / x.size(0)\n"
    "            lam  = self.cosine_increase_lambda(0., self.cfg.local_gates_lambda)\n"
    "            return lam * reg + gtcr * self.cfg.gtcr_lambda\n"
    "        return torch.tensor(0., device=x.device, requires_grad=True)\n"
    "\n"
    "\n"
    "print('Ablation subclasses (_NoReg, _NoLatentNoise, _NoInputNoise, _NoRecon) defined.')"
))

# ── CELL 24 ──────────────────────────────────────────────────────────────────
cells.append(code_cell(
    "RUN_ABLATION = False   # Set True (GPU, ~700 epochs x 6 variants)\n"
    "ABL_SEEDS    = 1       # Set to 10 for paper-level reproduction\n"
    "\n"
    "abl_results = {}\n"
    "\n"
    "if RUN_ABLATION:\n"
    "    VARIANTS = [\n"
    "        ('IDC (full)',              BaseModule),\n"
    "        ('IDC w/o Lreg',           _NoReg),\n"
    "        ('IDC w/o latent denoise', _NoLatentNoise),\n"
    "        ('IDC w/o input denoise',  _NoInputNoise),\n"
    "        ('IDC w/o Lrecon',         _NoRecon),\n"
    "    ]\n"
    "    for name, cls in VARIANTS:\n"
    "        print(f'\\nAblation: {name}')\n"
    "        accs, aris, nmis = [], [], []\n"
    "        for seed in range(ABL_SEEDS):\n"
    "            m = train_idc(CFG_M60K, seed=seed, log_dir=f'results/exp6/{name}',\n"
    "                          module_cls=cls, verbose=False)\n"
    "            accs.append(m.best_acc * 100); aris.append(m.best_ari * 100); nmis.append(m.best_nmi * 100)\n"
    "            print(f'  seed {seed}: ACC={accs[-1]:.1f}')\n"
    "        abl_results[name] = (np.mean(accs), np.mean(aris), np.mean(nmis))\n"
    "\n"
    "    # IDC features + K-Means: train full IDC, then apply K-Means to gated features\n"
    "    print('\\nAblation: IDC features + K-Means')\n"
    "    accs_km, aris_km, nmis_km = [], [], []\n"
    "    for seed in range(ABL_SEEDS):\n"
    "        m    = train_idc(CFG_M60K, seed=seed, log_dir='results/exp6/kmeans', verbose=False)\n"
    "        X_f, Y_f, _, G_f, _ = get_predictions(m, m.val_dataset)\n"
    "        sparse_X = X_f * (G_f > 0.5)\n"
    "        km_pred  = KMeans(n_clusters=10, random_state=seed, n_init=10).fit_predict(sparse_X)\n"
    "        accs_km.append(get_accuracy(km_pred, Y_f, 10) * 100)\n"
    "        aris_km.append(adjusted_rand_score(Y_f, km_pred) * 100)\n"
    "        nmis_km.append(normalized_mutual_info_score(Y_f, km_pred) * 100)\n"
    "    abl_results['IDC features + K-Means'] = (np.mean(accs_km), np.mean(aris_km), np.mean(nmis_km))\n"
    "\n"
    "else:\n"
    "    print('RUN_ABLATION=False — Table 5 shows paper values. Set True to run.')"
))

# ── CELL 25 ──────────────────────────────────────────────────────────────────
cells.append(code_cell(
    "T5_PAPER = [\n"
    "    # (name, paper_acc, paper_ari, paper_nmi, delta_acc, delta_ari, delta_nmi)\n"
    "    ('IDC (full)',              87.9, 82.8, 85.1,   0.0,  0.0,  0.0),\n"
    "    ('IDC w/o Lreg',           85.9, 81.2, 84.7, -2.0, -1.6, -0.4),\n"
    "    ('IDC w/o latent denoise', 86.5, 80.9, 83.2, -1.4, -1.9, -1.9),\n"
    "    ('IDC w/o input denoise',  84.3, 80.0, 83.9, -3.6, -2.8, -1.2),\n"
    "    ('IDC features + K-Means', 65.5, 49.3, 57.6,-22.4,-33.5,-27.5),\n"
    "    ('IDC w/o Lrecon',         18.0,  2.6,  4.3,-69.9,-80.2,-80.8),\n"
    "]\n"
    "\n"
    "rows5 = []\n"
    "for name, ap, ar, an, da, dr, dn in T5_PAPER:\n"
    "    pstr = (f'{ap:.1f}({da:+.1f})' if da != 0 else f'{ap:.1f}',\n"
    "            f'{ar:.1f}({dr:+.1f})' if dr != 0 else f'{ar:.1f}',\n"
    "            f'{an:.1f}({dn:+.1f})' if dn != 0 else f'{an:.1f}')\n"
    "    if name in abl_results:\n"
    "        a, ar_, n = abl_results[name]\n"
    "        ostr = (f'{a:.1f}', f'{ar_:.1f}', f'{n:.1f}')\n"
    "    else:\n"
    "        ostr = ('\u2014', '\u2014', '\u2014')\n"
    "    rows5.append([name, pstr[0], ostr[0], pstr[1], ostr[1], pstr[2], ostr[2]])\n"
    "\n"
    "df5 = pd.DataFrame(rows5, columns=['Model', 'ACC(paper)', 'ACC(ours)', 'ARI(paper)', 'ARI(ours)', 'NMI(paper)', 'NMI(ours)'])\n"
    "print('Table 5: Ablation Study on MNIST60K\\n')\n"
    "print(df5.to_string(index=False))\n"
    "\n"
    "# Bar chart of paper ACC values\n"
    "names5 = [r[0] for r in T5_PAPER]\n"
    "accs5  = [r[1] for r in T5_PAPER]\n"
    "fig, ax = plt.subplots(figsize=(10, 4))\n"
    "cols5   = ['steelblue'] + ['#e07070'] * (len(names5) - 1)\n"
    "bars    = ax.barh(names5[::-1], accs5[::-1], color=cols5[::-1], edgecolor='k', linewidth=0.5)\n"
    "for bar, val in zip(bars, accs5[::-1]):\n"
    "    ax.text(val + 0.5, bar.get_y() + bar.get_height() / 2,\n"
    "            f'{val:.1f}%', va='center', fontsize=9)\n"
    "ax.set_xlabel('ACC (%)', fontsize=11)\n"
    "ax.set_title('Table 5: Ablation Study on MNIST60K (paper values, blue=full IDC)', fontsize=11)\n"
    "ax.set_xlim(0, 100)\n"
    "plt.tight_layout()\n"
    "plt.savefig('results/exp6_ablation.png', dpi=120)\n"
    "plt.show()"
))

# ── CELL 26 ──────────────────────────────────────────────────────────────────
cells.append(md_cell("---\n## Final Summary"))

# ── CELL 27 ──────────────────────────────────────────────────────────────────
cells.append(code_cell(
    "print('=' * 65)\n"
    "print('RECONSTRUCTION SUMMARY')\n"
    "print('=' * 65)\n"
    "\n"
    "print('\\n[Exp 1] Synthetic Dataset')\n"
    "try:\n"
    "    print(f'  ACC  : {acc_s*100:.2f}%  (paper: 99.91%)')\n"
    "    print(f'  F1   : {np.mean(f1s)*100:.2f}%  (paper: 88.95%)')\n"
    "except: print('  Not run.')\n"
    "\n"
    "print('\\n[Exp 2] MNIST10K Interpretability (Table 1) — IDC row')\n"
    "print(f'  ACC          : {idc_t1[\"acc\"]:.2f}   (paper: 83.45)')\n"
    "print(f'  Uniqueness   : {idc_t1[\"uniq\"]:.2f}   (paper: 0.69)')\n"
    "print(f'  Diversity    : {idc_t1[\"div\"]:.1f}  (paper: 94.8)')\n"
    "print(f'  Faithfulness : {idc_t1[\"faith\"]:.2f}   (paper: 0.96)')\n"
    "print(f'  Generaliz.   : {idc_t1[\"gen\"]:.1f}  (paper: 88.5)')\n"
    "\n"
    "print('\\n[Exp 3] Real Tabular (Table 2)')\n"
    "if our_t2:\n"
    "    for ds, (m, s) in our_t2.items():\n"
    "        paper_v = TABLE2_PAPER.get('IDC (paper)', {}).get(ds, ('?',))[0]\n"
    "        print(f'  {ds:12s}: {m:.1f}+/-{s:.1f}  (paper: {paper_v})')\n"
    "else: print('  No datasets available.')\n"
    "\n"
    "print('\\n[Exp 4] Image Domain (Tables 3 & 4)')\n"
    "if exp4:\n"
    "    for k, v in exp4.items(): print(f'  {k}: {v}')\n"
    "else: print('  Not run (set RUN_* flags above).')\n"
    "\n"
    "print(f'\\n[Exp 5] NUDFT  |  ALLAML available: {RUN_NUDFT}')\n"
    "\n"
    "print('\\n[Exp 6] Ablation (Table 5)')\n"
    "if abl_results:\n"
    "    for n, v in abl_results.items(): print(f'  {n}: ACC={v[0]:.1f}')\n"
    "else: print('  Not run (set RUN_ABLATION=True).')\n"
    "\n"
    "print('\\n' + '=' * 65)"
))

# ── Build notebook dict ───────────────────────────────────────────────────────
notebook = {
    "nbformat": 4,
    "nbformat_minor": 5,
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3"
        },
        "language_info": {
            "name": "python",
            "version": "3.9.0"
        }
    },
    "cells": cells
}

out_path = (
    r"C:\Users\nadav\OneDrive\university\2nd_math_degree"
    r"\data_science_seminar\analyzing_the_article"
    r"\Interpretable_Deep_Clustering_analysis\IDC_Reconstruction.ipynb"
)

with open(out_path, "w", encoding="utf-8") as f:
    json.dump(notebook, f, ensure_ascii=False, indent=1)

print(f"Written: {out_path}")
print(f"Cells  : {len(cells)}")
